# frozen_string_literal: true

source "https://rubygems.org"

gem "puma"
gem "rails", "~> 8.0"
gem "zabon", path: ".."

# Optional: add sentry-ruby and sentry-rails to see Sentry context integration.
# gem "sentry-ruby"
# gem "sentry-rails"
